class IMU:
    def __init__(self, version: int = ...) -> None: ...
    def read_acc(self) -> Vector3D: ...
    def read_gyr(self) -> Vector3D: ...
    def read_mag(self) -> Vector3D: ...

class Vector3D:
    def __init__(self, x: int, y: int, z: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def z(self) -> int: ...
