robots:
  - setup: "full_body"
    motor_type: "bionic"
    delta_change: 10
    body_parts:
      left_arm:
        start_id: 1
      right_arm:
        start_id: 7
      left_leg:
        start_id: 13
      right_leg:
        start_id: 19
    motor_config:
      arm:
        signs: [1, -1, 1, -1, 1, 1]
        increments: [4, 4, 4, 4, 4, 4]
        maximum_values: [60, 60, 60, 60, 0, 10]
        offsets: [0, 0, 0, 0, 0, 0]
      leg:
        signs: [1, -1, 1, -1, 1, -1]
        increments: [4, 4, 4, 4, 4, 4]
        maximum_values: [60, 60, 60, 60, 60, 60]
        offsets: [0, 0, 0, 0, 0, 0]
    params:
      - motor_id: "default"
        kp: 0.5
        kd: 0.1
  - setup: "right_arm"
    motor_type: "robstride"
    delta_change: 10
    body_parts:
      right_arm:
        start_id: 1
    motor_config:
      arm:
        signs: [1, -1, 1, -1, 1, 1]
        increments: [4, 4, 4, 4, 4, 4]
        maximum_values: [60, 60, 60, 60, 0, 10]
        offsets: [0, 0, 0, 0, 0, 0]
    params:
      - motor_id: "default"
        torque_limit: 50
        cur_kp: 0.1
        cur_ki: 0.1
        cur_fit_gain: 0.1
        speed_limit: 100
        current_limit: 100
        loc_kp: 0.1
        spd_kp: 0.1
        spd_ki: 0.1
        spd_fit_gain: 0.1
