[package]
name = "firmware-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "faux-rtos"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true }

# Internal workspace dependencies
actuators = { path = "../hardware/actuators" }
imu = { path = "../hardware/sensors/imu" }
communication = { path = "../communication" }
behavior = { path = "../behavior" }
robot-description = { path = "../robot-description" }
infrastructure = { path = "../infrastructure" }
inference = { path = "../inference" }