[package]
name = "imu"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
# anyhow = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
tokio-serial = { workspace = true }
nalgebra = { workspace = true }
pin-project = { workspace = true }
futures = { workspace = true }
enumflags2 = { workspace = true }
paste = { workspace = true }
futures-enum = { workspace = true }

# Internal dependencies
robot-description = { path = "../../../robot-description" }
infrastructure = { path = "../../../infrastructure" }
communication = { path = "../../../communication" }

[features]
default = ["nightly"]
nightly = ["infrastructure/nightly"]
