/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CAN Transmitter example
*              for ModusToolbox. The CAN node 1 transmits the button status
*              periodically over the CAN bus. Successful message transmission is
*              indicated by toggling the USER LED.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2022, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>

#include <robot.h>
#include <commands.h>



/*****************************************************************************
* Defines
******************************************************************************/
/* Declarations for System timer timing */
#define TICKS_PER_SECOND                    9           /* Ticks per Second */

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (0)

#define ticker_lim 				1152000

#define BUS_1 					6
#define BUS_2 					13
#define BUS_3 					19
#define BUS_4					25


static uint8_t bus_counter_1;
static uint8_t bus_counter_2;
static uint8_t bus_counter_3;
static uint8_t bus_counter_4;


static Motors motors;
//static Motor TestMotor;
static uint32_t counter;
static uint32_t ticker;



void init_motor(Motor* motor, float min_pos, float max_pos, int id) {
    motor->min_pos = min_pos;
    motor->max_pos = max_pos;
    motor->position = 0;
    motor->speed = 0;
    motor->torque = 0;
    motor->id = id;

}



void init_motors(int num_motors, Motors* motors) {
    motors->num_motors = num_motors;
    motors-> motors = (Motor*)malloc(num_motors * sizeof(Motor));
    for (int i = 0; i < num_motors; i++) {
        init_motor(&motors->motors[i], -90, 90, i + 1);
    }
}

/*******************************************************************************
* Variables
*******************************************************************************/
/* Variable for keeping track of Interrupt */
static volatile bool timer_interrupt_flag = false;

/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* Function called by system timer every 100 milliseconds. The button state is
* sampled and sent over the CAN bus to the receiver. The User LED is toggled to
* indicate successful transmission.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void SysTick_Handler(void)
{
	static bool alternator = true;
//	static uint64_t message;



// 	if (alternator) {
// //		message = get_position(&motors->motors[0]);
// //		update_data(&CAN_NODE_2_LMO_0, 2, message);
//     /* Update CAN message. Sample and send button state. */
//     // CAN_NODE_2_LMO_0.can_data_byte[0] = 0xE0;
//     // CAN_NODE_2_LMO_0.can_data_byte[1] = 0x01;

//     get_position(&CAN_NODE_2_LMO_0, &motors.motors[0]);

//     CAN_NODE_3_LMO_0.can_data_byte[0] = 0xE0;
// 	CAN_NODE_3_LMO_0.can_data_byte[1] = 0x01;

//     // XMC_CAN_MO_SetIdentifier(&CAN_NODE_2_LMO_0, 0x001);
//     XMC_CAN_MO_SetIdentifier(&CAN_NODE_3_LMO_0, 0x002);

// //    XMC_CAN_MO_SetIdentifier(XMC_CAN_MO_t *const can_mo, const uint32_t can_identifier)

//     /* Configure data to be transmitted and data length code */
//     // XMC_CAN_MO_UpdateData(&CAN_NODE_2_LMO_0);

//     /* Send data in CAN_NODE_LMO_0 */
//     // XMC_CAN_MO_Transmit(&CAN_NODE_2_LMO_0);


//     XMC_CAN_MO_UpdateData(&CAN_NODE_3_LMO_0);
//     XMC_CAN_MO_Transmit(&CAN_NODE_3_LMO_0);

    /* Toggle USER LED1 to indicate that the message is transmitted */
//    XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);

    if (bus_counter_1 == BUS_1) {
    	bus_counter_1 = 0;
    }

    if (bus_counter_2 == BUS_2) {
    	bus_counter_2 = BUS_1;
    }

    if (bus_counter_3 == BUS_3) {
    	bus_counter_3 = BUS_2;
    }

    if (bus_counter_4 == BUS_4) {
    	bus_counter_4 = BUS_3;
    }
  
    if (alternator) {
    	set_position(&CAN_NODE_1_LMO_0, &motors.motors[bus_counter_1], 0.001, 0.001, 0.001, 0.001, 0.001);
		set_position(&CAN_NODE_2_LMO_0, &motors.motors[bus_counter_2], 0.001, 0.001, 0.001, 0.001, 0.001);
		set_position(&CAN_NODE_3_LMO_0, &motors.motors[bus_counter_3], 0.001, 0.001, 0.001, 0.001, 0.001);
		set_position(&CAN_NODE_4_LMO_0, &motors.motors[bus_counter_4],0.001, 0.001, 0.001, 0.001, 0.001);


	}

	else {
		set_position(&CAN_NODE_1_LMO_0, &motors.motors[bus_counter_1], 10, 12, 14, 15, 18);
		set_position(&CAN_NODE_2_LMO_0, &motors.motors[bus_counter_2], 10, 12, 14, 15, 18);
		set_position(&CAN_NODE_3_LMO_0, &motors.motors[bus_counter_3], 10, 12, 14, 15, 18);
		set_position(&CAN_NODE_4_LMO_0, &motors.motors[bus_counter_4], 10, 12, 14, 15, 18);




//    CAN_NODE_2_LMO_0.can_data_byte[1] = 0x02;
//    CAN_NODE_3_LMO_0.can_data_byte[1] = 0x02;
//
//    XMC_CAN_MO_SetIdentifier(&CAN_NODE_2_LMO_0, 0x7FF);
//    XMC_CAN_MO_SetIdentifier(&CAN_NODE_3_LMO_0, 0x7FF);
//
//
//
//    XMC_CAN_MO_UpdateData(&CAN_NODE_2_LMO_0);
//
//    XMC_CAN_MO_SetDataLengthCode(&CAN_NODE_2_LMO_0, 8);
//
//
//        /* Send data in CAN_NODE_LMO_0 */
//	XMC_CAN_MO_Transmit(&CAN_NODE_2_LMO_0);
//
//	XMC_CAN_MO_UpdateData(&CAN_NODE_3_LMO_0);
//
//	        /* Send data in CAN_NODE_LMO_0 */
//	XMC_CAN_MO_Transmit(&CAN_NODE_3_LMO_0);
//	XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
	}

	counter ++;

	//  alternator = !alternator;
	bus_counter_1 ++;
    bus_counter_2 ++;
	bus_counter_3 ++;
	bus_counter_4 ++;

    /* Timer interrupt occurs, set the flag to true  */
    timer_interrupt_flag = true;
}




/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. This function performs
*  - initial setup of device
*  - initialize CAN transmit message object and node
*  - can_message a CAN frame periodically
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/

/*
 * By sending alternating messages through a single CAN Node, we are able to reach around 10 messages a second at 10 ticks a second
 *
 *
 *Have to have a tick rate of at least 9 to being the SysTick Handler.
 *
 *
 */


int main(void)
{

    bus_counter_1 = 0;
    bus_counter_2 = BUS_1;
    bus_counter_3 = BUS_2;
    bus_counter_4 = BUS_3;



    cy_rslt_t result;
    init_motors(25, &motors);
    ticker = 0;

//    init_motor(&TestMotor, -90, 90, 1);


    #if ENABLE_XMC_DEBUG_PRINT
    /* Assign false to disable printing of debug messages */
    static volatile bool debug_printf = true;
    #endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize printf retarget */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    #if ENABLE_XMC_DEBUG_PRINT
    printf("Initialization done\r\n");
    printf("Initializing\r\n");
    #endif

    /* Enable system timer */
    SysTick_Config(SystemCoreClock / TICKS_PER_SECOND);

    while(1)
    {
        #if ENABLE_XMC_DEBUG_PRINT
        if(timer_interrupt_flag == true && debug_printf == true)
        {
            printf("CAN frame sent\r\n");
            debug_printf = false;
        }
        #endif
        if (ticker >= ticker_lim) {
        	printf("Decimal: %" PRIu32 "\r\n", counter);
        	printf("Hexadecimal: 0x%" PRIx32 "\r\n", counter);
        	ticker = 0;
        }
        ticker ++;

    }
}

/* [] END OF FILE */
